#!/bin/bash
# upload - uploades to repository
if [ -n "$1" ]; then
  #cd /root/OrgsyncWebsite/auvt-website
  echo -e "$(tput setaf 5)hg addremove$(tput sgr0)"
  hg addremove
  echo -e "$(tput setaf 5)hg commit -u spsuauvt -m \"$1\"$(tput sgr0)"
  hg commit -u spsuauvt -m "$1"
  echo -e "$(tput setaf 5)hg push$(tput sgr0)"
  hg push
fi

